// Code generated by MockGen. DO NOT EDIT.
// Source: process/base.go

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	exec "os/exec"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProcessInterface is a mock of ProcessInterface interface.
type MockProcessInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessInterfaceMockRecorder
}

// MockProcessInterfaceMockRecorder is the mock recorder for MockProcessInterface.
type MockProcessInterfaceMockRecorder struct {
	mock *MockProcessInterface
}

// NewMockProcessInterface creates a new mock instance.
func NewMockProcessInterface(ctrl *gomock.Controller) *MockProcessInterface {
	mock := &MockProcessInterface{ctrl: ctrl}
	mock.recorder = &MockProcessInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessInterface) EXPECT() *MockProcessInterfaceMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockProcessInterface) Cleanup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup")
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockProcessInterfaceMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockProcessInterface)(nil).Cleanup))
}

// GetCmd mocks base method.
func (m *MockProcessInterface) GetCmd() *exec.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCmd")
	ret0, _ := ret[0].(*exec.Cmd)
	return ret0
}

// GetCmd indicates an expected call of GetCmd.
func (mr *MockProcessInterfaceMockRecorder) GetCmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCmd", reflect.TypeOf((*MockProcessInterface)(nil).GetCmd))
}

// GetExecCommand mocks base method.
func (m *MockProcessInterface) GetExecCommand() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecCommand")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExecCommand indicates an expected call of GetExecCommand.
func (mr *MockProcessInterfaceMockRecorder) GetExecCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecCommand", reflect.TypeOf((*MockProcessInterface)(nil).GetExecCommand))
}

// GetPgId mocks base method.
func (m *MockProcessInterface) GetPgId() uintptr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPgId")
	ret0, _ := ret[0].(uintptr)
	return ret0
}

// GetPgId indicates an expected call of GetPgId.
func (mr *MockProcessInterfaceMockRecorder) GetPgId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPgId", reflect.TypeOf((*MockProcessInterface)(nil).GetPgId))
}

// GetStderrBuffer mocks base method.
func (m *MockProcessInterface) GetStderrBuffer() *bytes.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStderrBuffer")
	ret0, _ := ret[0].(*bytes.Buffer)
	return ret0
}

// GetStderrBuffer indicates an expected call of GetStderrBuffer.
func (mr *MockProcessInterfaceMockRecorder) GetStderrBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStderrBuffer", reflect.TypeOf((*MockProcessInterface)(nil).GetStderrBuffer))
}

// GetStdoutBuffer mocks base method.
func (m *MockProcessInterface) GetStdoutBuffer() *bytes.Buffer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStdoutBuffer")
	ret0, _ := ret[0].(*bytes.Buffer)
	return ret0
}

// GetStdoutBuffer indicates an expected call of GetStdoutBuffer.
func (mr *MockProcessInterfaceMockRecorder) GetStdoutBuffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStdoutBuffer", reflect.TypeOf((*MockProcessInterface)(nil).GetStdoutBuffer))
}

// IsRunning mocks base method.
func (m *MockProcessInterface) IsRunning() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockProcessInterfaceMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockProcessInterface)(nil).IsRunning))
}

// Resume mocks base method.
func (m *MockProcessInterface) Resume() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume")
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockProcessInterfaceMockRecorder) Resume() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockProcessInterface)(nil).Resume))
}

// Run mocks base method.
func (m *MockProcessInterface) Run(arg0 *uintptr, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockProcessInterfaceMockRecorder) Run(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProcessInterface)(nil).Run), arg0, arg1)
}

// Suspend mocks base method.
func (m *MockProcessInterface) Suspend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend")
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockProcessInterfaceMockRecorder) Suspend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockProcessInterface)(nil).Suspend))
}

// WaitTillFinished mocks base method.
func (m *MockProcessInterface) WaitTillFinished() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitTillFinished")
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitTillFinished indicates an expected call of WaitTillFinished.
func (mr *MockProcessInterfaceMockRecorder) WaitTillFinished() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitTillFinished", reflect.TypeOf((*MockProcessInterface)(nil).WaitTillFinished))
}
